// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {remote} from '../models';
import {server} from '../models';
import {main} from '../models';
import {printer} from '../models';
import {mdns} from '../models';

export function AddRemoteDevice(arg1:string,arg2:Array<string>,arg3:number,arg4:string):Promise<void>;

export function GetAllRemotePrinters():Promise<Array<remote.RemotePrinter>>;

export function GetAuthToken():Promise<string>;

export function GetConnectedDevices():Promise<Array<remote.ConnectedDevice>>;

export function GetJobs():Promise<Array<server.PrintJob>>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetPrinters():Promise<Array<printer.PrinterInfo>>;

export function GetRemotePrinters(arg1:string):Promise<Array<remote.RemotePrinter>>;

export function GetServerName():Promise<string>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function GetVirtualPrinterDir():Promise<string>;

export function IsAutoLaunchEnabled():Promise<boolean>;

export function PrintToRemote(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function RemoveRemoteDevice(arg1:string):Promise<void>;

export function ScanForDevices():Promise<Array<mdns.DiscoveredDevice>>;

export function SelectVirtualPrinterDir():Promise<string>;

export function SetAutoLaunch(arg1:boolean):Promise<void>;

export function TogglePrinterShare(arg1:string,arg2:boolean):Promise<void>;

export function UpdateServerName(arg1:string):Promise<void>;

export function UpdateVirtualPrinterDir(arg1:string):Promise<void>;
