// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRemoteDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRemoteDevice'](arg1, arg2, arg3);
}

export function GetAllRemotePrinters() {
  return window['go']['main']['App']['GetAllRemotePrinters']();
}

export function GetConnectedDevices() {
  return window['go']['main']['App']['GetConnectedDevices']();
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPrinters() {
  return window['go']['main']['App']['GetPrinters']();
}

export function GetRemotePrinters(arg1) {
  return window['go']['main']['App']['GetRemotePrinters'](arg1);
}

export function GetServerName() {
  return window['go']['main']['App']['GetServerName']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetVirtualPrinterDir() {
  return window['go']['main']['App']['GetVirtualPrinterDir']();
}

export function IsAutoLaunchEnabled() {
  return window['go']['main']['App']['IsAutoLaunchEnabled']();
}

export function PrintToRemote(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PrintToRemote'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RemoveRemoteDevice(arg1) {
  return window['go']['main']['App']['RemoveRemoteDevice'](arg1);
}

export function ScanForDevices() {
  return window['go']['main']['App']['ScanForDevices']();
}

export function SelectVirtualPrinterDir() {
  return window['go']['main']['App']['SelectVirtualPrinterDir']();
}

export function SetAutoLaunch(arg1) {
  return window['go']['main']['App']['SetAutoLaunch'](arg1);
}

export function TogglePrinterShare(arg1, arg2) {
  return window['go']['main']['App']['TogglePrinterShare'](arg1, arg2);
}

export function UpdateServerName(arg1) {
  return window['go']['main']['App']['UpdateServerName'](arg1);
}

export function UpdateVirtualPrinterDir(arg1) {
  return window['go']['main']['App']['UpdateVirtualPrinterDir'](arg1);
}
